application: nateandpaigeswedding
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /guestbook.html
  script: guestbook.py

- url: /signguestbook
  script: guestbook.py

- url: /(.*)
  script: welcome.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.xcf$
- ^(.*/)?.*\.json$
- maps_api_key
- todo