application: nateandpaigeswedding
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /guestbook.html
  script: guestbook.py

- url: /signguestbook
  script: guestbook.py

- url: /
  static_files: static/welcome.html
  upload: static/welcome.html

- url: /(.*)
  static_files: static/\1
  upload: static/(.*)
