application: nateandpaigeswedding
version: 3
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /(.*)
  script: application.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.xcf$
- ^(.*/)?.*\.json$
- ^(.*/)?.*/maps/.*
- ^(.*/)?.*/css/blueprint/src/.*
- ^(.*/)?.*/images/gimp/.*
- todo